### ISSUE TITLE
Fix your margins 

### ISSUE THREAD

**Issue by SpencerCDixon** [areinei123/Shoppr#27]
![screen shot 2015-06-09 at 4 04 40 pm](https://cloud.githubusercontent.com/assets/7471018/8068358/6c09faf6-0ec1-11e5-9f61-23a415993a33.png)

also, what is this app? make a read me. and make me collaborator

**Comment by Dodie324** [comment]
Dannnng, sup Spence!

It was an app we worked on for Angel Hack.

**Comment by fredchaps** [comment]
Its nice to talk to you too Spence.

I'll fix em, and add you as a collaborator, just don't go around messing
things up. Its gonna make us millions!

Frederick H Chapman
Glenville Tavern Services
   Secretary
The Glenville Stops
   Manager

**Comment by fredchaps** [comment]
Fixed
